# Comment that will be sent if an issue is judged to be closed
comment: "This issue is closed because it does not meet our criteria listed in the issue template."
issueConfigs:
- content:
  - "Version of OS(s) listed above with issue"
  - "Expected Behavior"
  - "Actual Behavior"
- content:
  - "Summary"
  - "API Changes"
  - "Intended Use Case"
