resources:
- repo: self

pool:
  name: Azure Pipelines
  demands: msbuild

variables:
  BuildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core SDK 3.x'
  inputs:
    version: 3.1.x

- task: MSBuild@1
  displayName: 'Build & Pack'
  inputs:
    solution: Build.sln
    msbuildVersion: 16.0
    msbuildArchitecture: x64
    configuration: Release
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber)-beta /p:PackageOutputPath=$(build.artifactstagingdirectory)/public  /p:AssemblyFileVersion=$(Build.BuildNumber) /p:JavaSdkDirectory="$(JAVA_HOME)/"'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory) '
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory) '

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'